version: '3'
services:
  react-app:
    build:
      context: ./frontend 
    ports:
      - "5173:5173" 
    environment:
      - REACT_APP_BACKEND_URL=http://rust-app:3030 

  rust-app:
    build:
      context: ./backend 
    ports:
      - "3030:3030"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: